### ISSUE TITLE
akka sample failing

### ISSUE THREAD

**Issue by mattmoor** [paketo-buildpacks/samples#21]
This morning I saw a string of failures in the akka sample with:

```
  [build] [error] sbt.librarymanagement.ResolveException: Error downloading com.typesafe.sbt:sbt-native-packager;sbtVersion=1.0;scalaVersion=2.12:1.7.5
  [build] [error]   Not found
  [build] [error]   Not found
  [build] [error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-native-packager_2.12_1.0/1.7.5/sbt-native-packager-1.7.5.pom
  [build] [error]   not found: /home/cnb/.ivy2/local/com.typesafe.sbt/sbt-native-packager/scala_2.12/sbt_1.0/1.7.5/ivys/ivy.xml
  [build] [error]   download error: Caught java.net.UnknownHostException: repo.scala-sbt.org (repo.scala-sbt.org) while downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-native-packager/scala_2.12/sbt_1.0/1.7.5/ivys/ivy.xml
  [build] [error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-native-packager/scala_2.12/sbt_1.0/1.7.5/ivys/ivy.xml
  [build] [error] Error downloading io.spray:sbt-revolver;sbtVersion=1.0;scalaVersion=2.12:0.9.1
  [build] [error]   Not found
  [build] [error]   Not found
  [build] [error]   not found: https://repo1.maven.org/maven2/io/spray/sbt-revolver_2.12_1.0/0.9.1/sbt-revolver-0.9.1.pom
  [build] [error]   not found: /home/cnb/.ivy2/local/io.spray/sbt-revolver/scala_2.12/sbt_1.0/0.9.1/ivys/ivy.xml
  [build] [error]   download error: Caught java.net.UnknownHostException: repo.scala-sbt.org (repo.scala-sbt.org) while downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/io.spray/sbt-revolver/scala_2.12/sbt_1.0/0.9.1/ivys/ivy.xml
  [build] [error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/io.spray/sbt-revolver/scala_2.12/sbt_1.0/0.9.1/ivys/ivy.xml
  [build] [error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:249)
  [build] [error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$35(CoursierDependencyResolution.scala:218)
  [build] [error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
  [build] [error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:218)
  [build] [error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
  [build] [error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:52)
  [build] [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:102)
  [build] [error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:69)
  [build] [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:115)
  [build] [error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
  [build] [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:115)
  [build] [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:96)
  [build] [error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
  [build] [error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:129)
  [build] [error] 	at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:2950)
  [build] [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
  [build] [error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
  [build] [error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
  [build] [error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
  [build] [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
  [build] [error] 	at sbt.Execute.work(Execute.scala:290)
  [build] [error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
  [build] [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
  [build] [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
  [build] [error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  [build] [error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
  [build] [error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  [build] [error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  [build] [error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  [build] [error] 	at java.base/java.lang.Thread.run(Thread.java:834)
  [build] [error] (update) sbt.librarymanagement.ResolveException: Error downloading com.typesafe.sbt:sbt-native-packager;sbtVersion=1.0;scalaVersion=2.12:1.7.5
  [build] [error]   Not found
  [build] [error]   Not found
  [build] [error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-native-packager_2.12_1.0/1.7.5/sbt-native-packager-1.7.5.pom
  [build] [error]   not found: /home/cnb/.ivy2/local/com.typesafe.sbt/sbt-native-packager/scala_2.12/sbt_1.0/1.7.5/ivys/ivy.xml
  [build] [error]   download error: Caught java.net.UnknownHostException: repo.scala-sbt.org (repo.scala-sbt.org) while downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-native-packager/scala_2.12/sbt_1.0/1.7.5/ivys/ivy.xml
  [build] [error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-native-packager/scala_2.12/sbt_1.0/1.7.5/ivys/ivy.xml
  [build] [error] Error downloading io.spray:sbt-revolver;sbtVersion=1.0;scalaVersion=2.12:0.9.1
  [build] [error]   Not found
  [build] [error]   Not found
  [build] [error]   not found: https://repo1.maven.org/maven2/io/spray/sbt-revolver_2.12_1.0/0.9.1/sbt-revolver-0.9.1.pom
  [build] [error]   not found: /home/cnb/.ivy2/local/io.spray/sbt-revolver/scala_2.12/sbt_1.0/0.9.1/ivys/ivy.xml
  [build] [error]   download error: Caught java.net.UnknownHostException: repo.scala-sbt.org (repo.scala-sbt.org) while downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/io.spray/sbt-revolver/scala_2.12/sbt_1.0/0.9.1/ivys/ivy.xml
  [build] [error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/io.spray/sbt-revolver/scala_2.12/sbt_1.0/0.9.1/ivys/ivy.xml
  [build] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? rpc error: code = NotFound desc = an error occurred when try to find container "2285ed81062d424744b4219b849c1146ff5a1347be595f164d052f7b8e1f09a9": not found
```

You can see full logs here: https://github.com/mattmoor/mink/runs/1370168466?check_suite_focus=true#step:11:37897

**Comment by mattmoor** [comment]
cc @nebhale

**Comment by mattmoor** [comment]
looks like it may have been a transient thing, or something they fixed since the next run passed 🤷
